<?php View::content(); ?>
<?php echo Tag::js('jsapi') ?>
<div class="row">
    <div class="col-lg-6 text-center">
        <div class="panel-body">
            <a href="docmasleidos">Documentos más leidos</a>
        </div>                        
    </div>
    <div class="col-lg-6 text-center">
        <div class="panel-body">
            <a>Otra estadistica</a>
        </div>                        
    </div>
</div>
<?php echo Form::open() ?>
<div class="row">
    <div class="col-lg-12 text-center">
        <div class="panel-body">
            <label>Seleccione el rango de fechas en el que desea consultar los documentos m&aacute;s le&iacute;dos</label> </br>
            Desde: <?php echo Form::date('estadistica.inicio') ?> Hasta: <?php echo Form::date('estadistica.fin') ?> <input href="" type="submit" class="btn btn-primary" value="Consultar"/>
        </div>                        
    </div>
</div>
<div class="row">
    <div class="col-lg-6 ">
        <div class="panel-body">
            <div id="piechart_3d" style="width: 510px; height: 500px;"></div>

            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>

                        <th><strong>Nombre</strong></th>                    
                        <th><strong>lecturas</strong></th>

                    </tr>
                </thead>  
                <tbody>

                    <?php foreach ($doc->items as $item) : ?>
                        <tr>

                            <td><?php echo $item->nombredocumento ?> </td>
                            <td><?php echo $item->lecturas ?> </td>                        

                        </tr>
                    <?php endforeach; ?>
                </tbody>

            </table>
        </div>                        
    </div>
    <div class="col-lg-6 ">
        <div class="panel-body">
            <div id="chart_div" style="width: 515px; height: 500px;"></div>
            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>

                        <th><strong>Nombre</strong></th>                    
                        <th><strong>lecturas</strong></th>

                    </tr>
                </thead>  
                <tbody>

                    <?php foreach ($doc->items as $item) : ?>
                        <tr>

                            <td><?php echo $item->nombredocumento ?> </td>
                            <td><?php echo $item->lecturas ?> </td>                        

                        </tr>
                    <?php endforeach; ?>
                </tbody>

            </table>
        </div>                        
    </div>
</div>
<?php echo Form::close() ?>
<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
<?php if ($item != NULL) { ?>
                ['Documento', 'Lecturas'],
    <?php foreach ($doc->items as $item): ?>
                    [<?php echo "'" . $item->nombredocumento . "'" ?>, <?php echo "'" . $item->lecturas . "'" ?>],
    <?php endforeach; ?>
            ]);

<?php } ?>
        var options = {
            title: 'Documentos más leidos (Porcentaje)',
            is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
    }
</script>
<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {

        var data = google.visualization.arrayToDataTable([
<?php if ($item != NULL) { ?>
                ['Documento', 'Lecturas'],
    <?php foreach ($doc->items as $item): ?>
                    [<?php echo "'" . $item->nombredocumento . "'" ?>, <?php echo $item->lecturas ?>],
    <?php endforeach; ?>
            ]);

<?php } ?>
        var options = {
            title: 'Documentos más leidos',
            hAxis: {title: 'Documentos', titleTextStyle: {color: 'red'}}
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

        chart.draw(data, options);

    }
</script>