<?php Router::redirect("usuario/ingresar");?>
<div class="row">

<div class="col-sm-8">
    <br/>
    <br/>
    <br/>
    <br/>
    
</div>
<div class="col-sm-2">
     <?php echo Form::open(); // por defecto llama a la misma url ?>
       <input class="form-control" placeholder="Enter text">
</div>
    <div class="col-sm-2">
         <button type="submit" class="btn btn-default">Buscar</button>
         <?php echo Form::close() ?>
 </div>   

</div>
    