<div class="content"> 

    <h2>Mis Documentos</h2>
    <div>
        <?php echo Form::open(); ?>
        <table >
            <tr> 

                <th>&nbsp; 

                </th>
                <th>
            <div > <input type="submit" class="btn btn-primary" value="filtrar">    </div>
            </th>

            </tr>
            </tr>
        </table>
        <?php echo Form::close() ?>

    </div>
    <br>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                   
                    <th><strong>Nombre</strong></th>                    
                    <th><strong>fecha creacion</strong></th>

                </tr>
            </thead>  
            <tbody>
                <?php foreach ($inner->items as $item) : ?>
                    <tr>
                       
                        <td><?php echo $item->nombrecarpeta ?> </td>
                        <td><?php echo $item->fechacreacion_at ?> </td>                        
                        <td><?php echo Html::linkAction("abrir/$item->id/", 'Abrir') ?>
                            <?php echo Html::linkAction("crear", 'crear') ?>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>
    </div>
    <?php echo img_tag('graficas/grafica1.png');?>
    <?php View::partial('paginators/classic', false, array('page' => $inner, 'show' => 5, 'url' => 'carpeta/index')); ?>



</div>

