<!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Kumbia">SGD</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                
                
            
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> javier  pino </a>
                    
                </li>
                <li>
                    <a href="#" ><i class="fa fa-fw fa-power-off"></i> Cerrar Sesión </a>
                    
                </li>
            </ul>
            <ul class="nav navbar-right top-nav">
                
                    <?php echo Html::img('n.jpg','una imagen');?>
                    
                
            </ul>
            
            
            
       
        </nav>