<?php View::content(); ?>


<div class="form-group">
    <?php echo Form::open(); // por defecto llama a la misma url ?>
</div>

<div class="form-group">
    <?php echo Form::hidden('oculto') ?>
</div>
<div class="form-group">
    <input type="submit" onclick="return confirm('¿Está seguro que desea Eliminar documento?');
            return false;" class="btn btn-primary" value="Eliminar">

    <a href="http://localhost/trunk/carpeta/index" class="btn btn-primary" id="btn_cancelar">Cancelar</a>


</div>
<?php echo Form::close() ?>

