<div class="content"> 


    <div>
        <?php echo Form::open(); ?>
        <table >
            <tr> 

                <th>&nbsp;
                    <?php
                    $ar2 = array('Crear Carpeta', 'Crear Documento');
                    echo Form::Select('region', $ar2, 'Crear Carpeta');
                    ?>

                </th>
                <th> </th>

            </tr>

        </table>
        <?php echo Form::close() ?>

    </div>
    <br>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>

                    <th><strong>Nombre</strong></th>                    
                    <th><strong>fecha creacion</strong></th>

                </tr>
            </thead>  
            <tbody>
                <?php foreach ($inner->items as $item) : ?>
                    <tr>

                        <td><?php echo Html::linkAction("abrir/$item->id/", $item->nombrecarpeta) ?> </td>
                        <td><?php echo $item->fechacreacion_at ?> </td>                        
                        <td>
                            <?php echo Html::linkAction("crear/$item->id/", 'crear carpeta') ?>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

        </table>
    </div>
    
    <?php View::partial('paginators/classic', false, array('page' => $inner, 'show' => 5, 'url' => 'carpeta/index')); ?>



</div>

