


<div id="login">   
  <?php echo form_tag("usuario/ingresar"); ?>
  <div class="form-group">
    <div class="etiqueta" align="center"><label for="usuario">Usuario:</label></div>
    <div class="texto" align="center"><?php echo text_field_tag("usuario","size: 10"); ?></div>
  </div>
  <div class="form-group">
    <div class="etiqueta" align="center"><label for="contrasena">Clave:</label></div>
    <div class="texto" align="center"><?php echo password_field_tag("contrasena","size: 10"); ?></div>
  </div>
  <div class="form-group">
    <?php echo submit_tag("Ingresar","class: btn btn-lg btn-success btn-block"); ?>
  </div>
    <div>
        <a href="restaurar">¿No puede acceder a su cuenta?</a><br>
        <a href="crear">Cree su cuenta</a>
    </div>
  <?php echo end_form_tag(); ?>
</div>

