<?php $titulo = 'Crear Documento'; ?>
 
    <p class="text-center">Los campos con (*) son obligatorios</p>
    <?php echo Form::open(); ?>
     <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 text-center">
            <div class="panel-body">
                Nombre Documento(*):</br><?php echo Form::text('nuevodocumento.NOMBREOCUMENTO') ?><!--<input type="text" id="txt_nombre">!-->
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-4 text-center">
            <div class="panel-body">
               Fecha Publicación: </br><?php echo Form::date('documento.FECHAPUBLICACION') ?><!--<input type="text" id="txt_fecha" size="52px"></br>!-->
            </div>                        
        </div>
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
   
     <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 text-center">
            <div class="panel-body">
                Descripción Corta(*):</br> <textarea class="form-control" rows="3"></textarea>
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    
    <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 text-center">
            <div class="panel-body">
                Palabras Clave(*):</br><?php echo Form::text('documento.PALABRAS') ?><!--<input type="text" id="txt_direccioncorreo" size="52px"></br>!-->
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    
    <div class="row">
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-4 text-center">
            <div class="panel-body">
               Folio(*): </br><?php echo Form::text('documento.FOLIO') ?><!--<input type="text" id="txt_extension" size="52px"></br>!-->
            </div>                        
        </div>
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 text-center">
            <div class="panel-body">
                Subir documento <input type="file" ><!--<input type="text" id="txt_celular" size="52px"></br>!-->
                
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-2 text-center">
            <div class="panel-body">
                <?php echo Form::submit('Guardar') ?><!--<input type="submit" value="Crear" id="btn_crear">!-->
            </div>                        
        </div>
        <div class="col-lg-2 text-center">
            <div class="panel-body">
                <input type="submit" value="Cancelar" id="btn_cancelar">
            </div>                        
        </div>
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>   
        
    <?php echo Form::close() ?>
