
<?php $titulo = 'Crear Documento'; ?>
 <?php echo Form::openMultipart(); ?>
    <p class="">Los campos con (*) son obligatorios</p>
     <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 ">
            <div class="panel-body">
                Nombre Documento(*):</br><?php echo Form::text('Documento.NOMBREDOCUMENTO') ?><!--<input type="text" id="txt_nombre">!-->
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 ">
            <div class="panel-body">
               Fecha Publicación: </br><?php echo Form::date('Documento.FECHAPUBLICACION_AT') ?><!--<input type="text" id="txt_fecha" size="52px"></br>!-->
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
   
     <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6">
            <div class="panel-body">
                Descripción Corta(*):</br> <?php echo Form::textarea('Docuemnto.DESCRIPCION') ?>
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    
    <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 ">
            <div class="panel-body">
                Palabras Clave(*):</br><?php echo Form::text('Documento.PALABRASCLAVE') ?><!--<input type="text" id="txt_direccioncorreo" size="52px"></br>!-->
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    
    <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 ">
            <div class="panel-body">
               Folio(*): </br><?php echo Form::text('Documento.FOLIO') ?><!--<input type="text" id="txt_extension" size="52px"></br>!-->
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-6 ">
            <div class="panel-body">
                Subir documento <?php echo Form::file('Documento.CONTENIDO')?>
            </div>                        
        </div>
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>        
    </div>
    <div class="row">
        <div class="col-lg-3 text-center">
            <div class="panel-body">
            </div>                        
        </div>
        <div class="col-lg-2 ">
            <div class="panel-body">
                <?php echo Form::submit('Guardar') ?><!--<input type="submit" value="Crear" id="btn_crear">!-->
            </div>                        
        </div>
        <div class="col-lg-2 text-center ">
            <div class="panel-body">
                <input type="submit" value="Cancelar" id="btn_cancelar">
            </div>                        
        </div>
        <div class="col-lg-4 text-center">
            <div class="panel-body">
            </div>                        
        </div>   
 </form>
