<?php View::content(); ?>
<?php $titulo = 'Cambiar Contraseña y/o nombre de Usuario de la cuenta en Sistema Gestión Documental PIS'; ?>
 
<p class="">Los campos con (*) son obligatorios</p>
    <?php echo Form::open(); ?>

    <div class="row">
        <div class="col-lg-12 ">
            <div class="panel-body">
                 Su nombre de Usuario es: 
            </div>                       
        </div>               
    </div>
    
    <div class="row">
    <div class="col-lg-12 ">
        <div class="panel-body">
            Contraseña Nueva(*): </br><?php echo Form::pass('Usuario.contrasena') ?>
            <h6>La contraseña debe tener mínimo 8 caracteres, debe incluir mínimo un número</h6>
        </div>                        
    </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-body">
                Confirmar Contraseña(*): <br><?php echo Form::pass('CONFIRMAR_CONTRASENA') ?><br/>
            </div>                        
        </div>
    </div>
 <div class="row">        
        <div class="col-lg-2 text-center">
            <div class="panel-body">
                <div class="form-group">
                    <a href="regresar"  class="btn btn-primary" >Guardar Contraseña</a>
                      
                </div> 
            </div>                        
        </div>
    </div>
 <?php echo Form::close() ?>