<!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Kumbia">SGD</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                
                
            
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Julian Rojas </a>
                    
                </li>
                <li>
                    <a href="#" ><i class="fa fa-fw fa-power-off"></i> Cerrar Sesión </a>
                    
                </li>
            </ul>
            
            
            
            
            <!-- Sidebar
            Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="javascript:;" data-toggle="collapse" >Empleados </a>
                        <ul >
                            <li>
                                <a href="/Kumbia/empleado"><i class="fa fa-fw fa-dashboard"></i>Inicio</a>
                            </li>
                            <li>
                                <a href="/Kumbia/empleado/create"><i class="fa fa-fw fa-edit"></i>Mis Documentos</a>
                            </li>
                            <li>
                                <a href="/Kumbia/empleado/create"><i class="fa fa-fw fa-bar-chart-o"></i>Estadisticas</a>
                            </li>
                            <li>
                                <a href="/Kumbia/empleado/create"><i class="fa fa-envelope"></i>Enviar Mensaje</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"></i> Departamentos </a>
                        <ul  >
                            <li>
                                <a href="/Kumbia/departamento"><i class="fa fa-fw fa-wrench"></i>Adminstrar Usuarios</a>
                            </li>
                            <li>
                                <a href="/Kumbia/departamento/create"><i class="fa fa-fw fa-edit"></i>Subir documento</a>
                            </li>
                        </ul>
                    </li>
                    
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </nav>