<?php View::content(); ?>
<?php echo Tag::js('jsapi') ?>
    <div class="row">
        <div class="col-lg-6 text-center">
            <div class="panel-body">
                <a href="docmasleidos">Documentos más leidos</a>
            </div>                        
        </div>
        <div class="col-lg-6 text-center">
            <div class="panel-body">
                <a>Otra estadistica</a>
            </div>                        
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 ">
            <div class="panel-body">
                <div id="piechart_3d" style="width: 510px; height: 500px;"></div>
            </div>                        
        </div>
        <div class="col-lg-6 ">
            <div class="panel-body">
                <div id="chart_div" style="width: 515px; height: 500px;"></div>
            </div>                        
        </div>
    </div>
        
        
        <script type="text/javascript">
            google.load("visualization", "1", {packages:["corechart"]});
            google.setOnLoadCallback(drawChart);
            function drawChart() {
              var data = google.visualization.arrayToDataTable([
                  <?php if($item != null){?>
                ['Task', 'Hours per Day'],
                <?php foreach ($doc->items as $item):?>
                ['<?php echo $item->nombredocumento ?>', <?php echo $item->lecturas ?>],
                <?php endforeach; ?>
                  <?php }?>
              ]);

              var options = {
                title: 'Documentos más leidos',
                is3D: true,
              };

              var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
              chart.draw(data, options);
            }
        </script>
        <script type="text/javascript">
                google.load("visualization", "1", {packages:["corechart"]});
		google.setOnLoadCallback(drawChart);
		function drawChart() {

		  var data = google.visualization.arrayToDataTable([
			['Year', 'Sales'],
			['2004',  1000],
			['2005',  1170],
			['2006',  660],
			['2007',  1030]
		  ]);

		  var options = {
			title: 'Company Performance',
			hAxis: {title: 'Year', titleTextStyle: {color: 'red'}}
		  };

		  var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

		  chart.draw(data, options);

		}
        </script>