<?php View::content(); ?>
<?php $titulo = 'Bienvenido: '  ?>
<?php Form::open(); ?>
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">Bienvenido a Sistema de Gestión Documental PIS Unicauca</br></br>
                          En este espacio usted podrá subir, crear, modificar, eliminar, mover y compartir documentos tipo .xsl, .jpg, .pdf, .doc, .txt, entre otros.</br>
                          También puede editar información de los usuarios registrados, dar de baja o permitir el acceso.</br></br>
                          &iexcl;Haz un buen uso de esta herramienta&excl;
    </div>
    <div class="col-lg-3"></div>
</div>
<?php Form::close()?>

