<html>
    <head>
        <?php $titulo = 'Recuperar contraseña'; ?>
    </head>
    <body>
        <div>
            <div class="texto"><label>Hemos enviado un mensaje a su correo electr&oacute;nico, por favor revise su cuenta</label></div>
        </div>
        <div class="form-group"></div>
        <div class="form-group">
            <a href="regresar" class="btn btn-lg btn-success btn-block">Regresar</a>
            
        </div>
    </body>
</html>

    
        
