  <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            <!--El titulo se manda desde el controlador  $this->titulo = "Crear usuario desde saludo controller";-->
                            <?php echo $titulo ?> 
                        </h1>
                        <!--Miga de pan-->
                            <ol class="breadcrumb">
                                <?php  View::partial('breadcrumb'); ?>
                            </ol>
                    </div>
                </div>
                <!-- /.row -->