  <!-- Page Heading -->
                
                    <div class="col-lg-12">
                        
                        <!--Miga de pan-->
                        <br>
                         <br>
                          
                           
                            <ol class="breadcrumb">
                                
                                <?php  View::partial('breadcrumb'); ?>
                            </ol>
                        <h2 class="page-header">
                            <!--El titulo se manda desde el controlador  $this->titulo = "Crear usuario desde saludo controller";-->
                            <?php echo $titulo ?>
                             </h2>
                        
                    </div>
                
                <!-- /.row -->