<div class="content"> 

    <h2>Usuarios</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th><strong>id</strong></th>
                    <th><strong>Nombres</strong></th>
                    <th><strong>apellido</strong></th>
                    <th><strong>Roll</strong></th>
                    <th><strong>Oficina</strong></th>
                    <th><strong>Acciones</strong></th>
                </tr>
            </thead>  
            <tbody>
                <?php foreach ($inner->items as $item) : ?>
                    <tr>
                        <td><?php echo $item->id ?> </td>
                        <td><?php echo $item->nombre ?> </td>
                        <td><?php echo $item->apellido ?> </td>
                        <td><?php echo $item->rol ?> </td>
                        <td><?php echo $item->oficina ?> </td>
                        <td><?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
                            <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
                                
                            </td>
                            
                       
                    </tr>
<?php endforeach; ?>
            </tbody>

        </table>
    </div>

<?php View::partial('paginators/classic', false, array('page' => $inner, 'show' => 5, 'url' => 'usuariocrud/index')); ?>



</div>

